version: '3'

services:

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - './data:/data/core'

  optimizer:
    build: optimizer/
    ports:
      - '8000:8000'
    depends_on:
      - mongodb
